// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyyjwtxctdmykdbqrpew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5eWp3dHhjdGRteWtkYnFycGV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMjA4NTIsImV4cCI6MjA2NjY5Njg1Mn0.diOR1scAdnodG7RIkv-dkbpJ9DrI--oYIq5eLNwiLzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);